samples: ["GTEx"] # sample names
out_dir: /data1/shahs3/users/preskaa/AMLproteogenomics/data/APS028_AML_PG2_analysis/GTEx_ORFs
ref_genome: /data1/shahs3/reference/ref-sarcoma/GTEx_v9/GRCh38.p10.genome.fa
transcripts: /data1/shahs3/reference/ref-sarcoma/GTEx_v9/flair_filter_transcripts.gtf
# swissprot fasta for use to blast against; will allow us to include potentially important proteins that showed up in the transdecoder search
swissprot_fasta: /data1/shahs3/reference/ref-sarcoma/blast_databases/swissprot_human_250206/2025-02-06-reviewed-isoforms-UP000005640.fas
# directory for diamond blast database
diamond_database_dir: /data1/shahs3/reference/ref-sarcoma/blast_databases/swissprot_human_250206/
diamond_db_prefix: 2025-02-06-reviewed-isoforms-UP000005640