cluster:
  mkdir -p logs/`date +"%y-%m-%d"`/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --time={resources.time}
    --output=logs/`date +"%y-%m-%d"`/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partition=componc_gpu,componc_cpu
  - mem_mb=20000
  - time=180
restart-times: 0 #temporary
max-jobs-per-second: 3
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 300
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: True